title: Melissa Benito
description: Personal website and portfolio
author:
  name: Melissa Benito
  twitter: melissabenito
  picture: /assets/images/melissabenito.jpg
github_username: melissabenito
twitter_username: melissabenito
instagram_username: meli.benito
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
- jekyll-remote-theme
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
